import {NextPage} from "next";
import Head from "next/head";
import client from '../lib/apollo-client';
import LocationsView from "../components/calendar/LocationsView";
import CalendarView from "../components/calendar/CalendarView";
import UserFormView from "../components/calendar/UserFormView";
import {GET_LOCATIONS} from "../graphql/GetLocations";
import StatusView from "../components/calendar/StatusView";

// @ts-ignore
const CalendarComponent: NextPage = ({locations, initialTimes}) => {
    return (
        <>
            <Head>
                <title>Calendar Component</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                {LocationsView(locations)}
                {CalendarView(initialTimes)}
                {UserFormView()}
                {StatusView()}
            </main>
        </>
    )
}

export default CalendarComponent

export async function getServerSideProps() {
    const { data } = await client.query({
        query: GET_LOCATIONS
    });

    return {
        props: {
            locations: data.testdrive_locations,
            initialTimes: ["11:00 AM", "2:00 PM"]
        },
    };
}