import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from "../components/home/hero";
import MeetSolo from "../components/home/MeetSolo";
import Footer from "../components/globals/Footer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ElectraMeccanica - Ingenious e-Mobility Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={''}>
          <div className="bg-white">
              <Hero />
              <MeetSolo />
              <Footer />
          </div>
      </main>
    </div>
  )
}

export default Home
